# Site settings
title: Memory 
SEOTitle: 阿坤的博客 | KUN Blog
header-img: img/post-bg-rwd.jpg
email: 167310@supinfo.com
description: "每个胜利背后都有许多尝试"
#keyword: "WEB, CDUA, 大数据, PHP"
url: "https://superkunkunkun.github.io"         
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Goals determine what you going to be!"
sidebar-avatar: img/avatar-by.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
#weibo_username:     阿坤memory
#zhihu_username:     xu-tong-kun-33
github_username:    superkunkunkun
#facebook_username:  baiying.qiu.7
#jianshu_username:   e71990ada2fd
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

# Build settings
markdown: kramdown
theme: minima
gems: 
  - jekyll-paginate
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
# Markdown settings
kramdown:
  input: GFM                    



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
#duoshuo_username: qiubaiying
# Share component is depend on Comment so we can NOT use share only.
#duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
#ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
#ga_domain: auto


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 3              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

